### ISSUE TITLE
Problem - Undefined method Aggregate

### ISSUE THREAD

**Issue by thiagocifani** [whoahbot/dm-redis-adapter#47]
Hello, I am using this adapter and after some updates and codification, I got a error trying to remove some items in a has_many relation. below follows the error stack:

undefined method `aggregate' for #DataMapper::Adapters::RedisAdapter:0x007febfb268ba0

dm-aggregates (1.0.2) lib/dm-aggregates/repository.rb:6:in `aggregate'
  dm-aggregates (1.0.2) lib/dm-aggregates/aggregate_functions.rb:185:in`aggregate'

I am using dm-core, dm-validations, dm-constraints to do dependent destroy AR work.

It seems this error is happening when I did some has 1 relation between my models. Something like:

https://gist.github.com/thiagocifani/5236698

please, if you have any idea what should I do to fix this error, let me know

have a nice day

**Comment by thiagocifani** [comment]
To complete this issue, I have a self reference relation in order_items, where a order_item can have many order_items.

In the belongs_to I've added a constraint destroy to delete children records

**Comment by thiagocifani** [comment]
apparently, It was a problem with my dm version. I was using 1.0.2 and when I upgrade to 1.2.0 it fixes the problem
